# Generated by Django 5.0.6 on 2025-02-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_plan_alter_user_options_user_hits_user_is_banned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'پلن', 'verbose_name_plural': 'پلن ها'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک ها'},
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
