# Generated by Django 5.0.6 on 2025-03-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
