# Generated by Django 5.0.6 on 2025-03-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_for_exemption',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
