# Generated by Django 5.0.6 on 2025-03-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_user_points_for_exemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='word_limit',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
