# Generated by Django 5.0.6 on 2025-02-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آدرس IP', 'verbose_name_plural': 'آدرس های IP'},
        ),
    ]
