# Generated by Django 5.0.6 on 2025-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_ipaddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
