# Generated by Django 5.0.6 on 2025-03-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_showads'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('i', 'اینستاگرام'), ('t', 'تلگرام'), ('f', 'فیسبوک'), ('w', 'واتساپ')], max_length=1)),
                ('link', models.URLField()),
            ],
        ),
    ]
