# Generated by Django 5.0.6 on 2025-03-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('a', 'درباره ما'), ('c', 'ارتباط با ما'), ('p', 'حریم خصوصی'), ('f', 'سوالات متداول'), ('m', 'ماموریت و چشم انداز')], max_length=1)),
                ('context', models.TextField()),
            ],
        ),
    ]
