# Generated by Django 5.0.6 on 2025-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_staticpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='choice',
            field=models.CharField(choices=[('i', 'اینستاگرام'), ('t', 'تلگرام'), ('f', 'فیسبوک'), ('w', 'واتساپ'), ('e', 'ایمیل')], max_length=1),
        ),
    ]
