# Generated by Django 5.0.6 on 2025-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0002_remove_ask_answer_ask_ask_to_ask_user_words_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name': 'کلمه', 'verbose_name_plural': 'کلمه\u200cها'},
        ),
        migrations.AddField(
            model_name='words',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], default='d', max_length=10),
        ),
    ]
