# Generated by Django 5.0.6 on 2025-03-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0004_alter_words_word_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='question',
            new_name='text',
        ),
    ]
