# Generated by Django 5.0.6 on 2025-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0005_rename_question_suggestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('r', 'رد شده')], default='d', max_length=10),
        ),
        migrations.AlterField(
            model_name='words',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('r', 'رد شده')], default='d', max_length=10),
        ),
    ]
