# Generated by Django 5.0.6 on 2025-03-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0006_suggestion_status_alter_words_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='کلمه')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
