# Generated by Django 5.2 on 2025-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0009_mostsearchedwords_alter_userfavorite_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mostsearchedwords',
            options={'verbose_name': 'بیشترین جست و جو', 'verbose_name_plural': 'بیشترین جست و جو ها'},
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_word',
            field=models.CharField(max_length=255),
        ),
    ]
