# Generated by Django 5.2 on 2025-04-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0010_alter_mostsearchedwords_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name': 'سابقه جست و جو', 'verbose_name_plural': 'سابقه جست و جو'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': 'کلمه مورد علاقه کاربر', 'verbose_name_plural': 'کلمات مورد علاقه کاربر'},
        ),
    ]
