# Generated by Django 5.2 on 2025-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0011_alter_searchhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite_word',
            field=models.CharField(max_length=255),
        ),
    ]
